# aliases
alias ll='ls -lt'
alias lll='ls -alt'
alias h='history'
alias more='less'
alias rm='rm -f'
alias f='find . -name '
alias netrestart='sudo service network restart'
alias net='netrestart'
alias rp='realpath'
alias psgrep='ps aux|grep'
alias algrep='alias|grep'
alias pingg='ping www.google.com'
alias pulsekill='pulseaudio --kill'
alias term1='gnome-terminal --geometry 175x47+0+0'
alias term2='gnome-terminal --geometry 175x47+400+0'
alias term3='gnome-terminal --geometry 175x47+200+0'

#alias java8='export JAVA_HOME=/home/nick/apps/java/java-1.8.0-openjdk-1.8.0.151-1.b12.el6_9.x86_64'
#alias java9='export JAVA_HOME=/home/nick/apps/java/jdk-9.0.4'
alias ccat='pygmentize -g'
alias ncat='pygmentize -g -O style=colorful,linenos=1'

alias mvncompile='mvn clean compile'
alias mvnotest='mvn clean install -Dmaven.test.skip=true'
alias mvnunitest='mvn test'
alias mvnitest='mvn clean test-compile failsafe:integration-test failsafe:verify'
alias mvntest='printf "\n\n";mvn clean install -f pom-it.xml'
alias mvnbuild='printf "\nmvn clean install\n";mvn clean install' 
alias mvne='printf "\n\n";mvn eclipse:eclipse'
alias springrun='mvn spring-boot:run'
alias fat='gradle fatJar'

alias gitd='clear;printf "\n\n";git diff'
alias gitb='printf "\n\n";git branch'
alias gits='clear;printf "\n\n";git status'
alias gitc='git checkout '
alias gitdc='git diff --color-words=.'
alias diffc='git diff --word-diff=color --no-index --word-diff-regex=.'
alias grso='clear;git remote show origin'
alias gfa='clear;git fetch --all'

alias dcls='docker container ls -a'
alias dcrm='docker container rm'
alias dcstop='docker container stop'
alias dcstart='docker container start'
alias dils='docker image ls'
alias dirm='docker rmi'
alias dlog='docker logs'

alias contstop='sudo service containerd stop'
alias contstart='sudo service containerd start'
alias contstatus='sudo service containerd status'

alias dccls='docker-compose ps'

alias vib='vi ~/.bashrc'
alias sbrc='source ~/.bash_aliases && alias'
alias vibrc='vi ~/.bashrc'

alias hgg='history|grep "git "'
alias hgc='history|grep commit|grep -v "grep"'
alias hgp='history|grep push|grep -v "grep"'

alias hgpdc='hg scp|grep pom|grep dap-common'
alias hgpsj='hg scp|grep pom|grep spark-job'
alias hgtdc='hg scp|grep tar|grep dap-common'
alias hgtsj='hg scp|grep tar|grep spark-job'

alias impala='impala-shell -i localhost'
alias ua='uname -a'
alias h='history 50'
alias hg='history|grep'
alias hdls='hadoop fs -ls' 
alias hdput='hadoop fs -put -f' 
alias g='grep -Hnr'
alias gfxf='grep -F -x -f'

alias cdtb='cd ~/git/thingsboard'
alias cdhi='cd ~/git/hitopbtc'
