version: '3.3'
services: 
  hitop-mysql:
    image: mysql:latest
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: hitop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: ThePassword
    expose:
      - 3306
    volumes:
      - hitop-db:/var/lib/mysql
  hitop:
    container_name: hitop
    #build:
    #  context: ./
    #  dockerfile: ./Dockerfile
    image: avlo/hitop:latest
    depends_on:
      - hitop-mysql
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: hitop
      DATABASE_USER: user 
      DATABASE_PASSWORD: password
      DATABASE_NAME: hitop  
      DATABASE_PORT: 3306
volumes:
  hitop-db:
